using NUnit.Framework;

namespace Human.Tests
{
    [TestFixture]
    class TeacherTests
    {
        [Test]
        TeachMethodTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}